# Generated by Django 3.2 on 2021-04-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('duration', models.TextField()),
                ('launch', models.DateField()),
                ('synopsis', models.TextField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.classification')),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
