# Generated by Django 3.2 on 2021-04-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210414_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criticism',
            old_name='starts',
            new_name='stars',
        ),
    ]
