# Generated by Django 3.2 on 2021-04-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_starts_criticism_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='critic_reviews',
            field=models.ManyToManyField(to='movies.Criticism'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_comments',
            field=models.ManyToManyField(to='movies.Comment'),
        ),
    ]
