# Generated by Django 3.2 on 2021-04-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20210415_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='classification',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
